# Generated by Django 3.1.5 on 2021-04-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Ismi')),
                ('email', models.EmailField(max_length=300, verbose_name='Email')),
                ('phone', models.CharField(max_length=300, verbose_name='Telfon raqami')),
                ('message', models.TextField(verbose_name='Xabar')),
            ],
            options={
                'verbose_name': 'Aloqa',
                'verbose_name_plural': 'Aloqalar',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ismi')),
                ('proyekt_name', models.CharField(max_length=500, verbose_name='Proyekt nomi')),
                ('image', models.ImageField(upload_to='Porfolio/', verbose_name='Proyekt rasmi')),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfoliolar',
            },
        ),
    ]
